---
- name: "Make backend dir"
  become: true
  command: mkdir backend

- name: "Copy files to server"
  become: true
  copy:
    src: "~/project/artifact.tar.gz"
    dest: "/home/ubuntu/backend/artifact.tar.gz"

- name: "Unzip files"
  command: tar -xzf artifact.tar.gz
  become: true
  args:
    chdir: /home/ubuntu/backend

- name: "Install dependencies"
  command: npm install
  become: true
  args:
    chdir: /home/ubuntu/backend

- name: "Run app with PM2"
  command: pm2 start npm -- start
  args:
    chdir: /home/ubuntu/backend
